### ISSUE TITLE
How to transform actions to local robot end effector frame

### ISSUE THREAD

**Issue by TongZhangTHU** [NVlabs/mimicgen_environments#12] opened 2024-03-26 03:45 UTC
Hi,

Thanks for your great work!  I've observed that the actions in the data utilize the "OSC_POSE" controller type, indicating they are defined in the global coordinate frame. However, I'm currently exploring the possibility of obtaining actions relative to the local frame of the robot's end effector, (which might align more closely with the "IK_POSE" controller type, see [https://github.com/ARISE-Initiative/robosuite/blob/48c1b8a6c077d04399a00db05694d7f9f876ffc9/docs/demos.md?plain=1#L37](https://github.com/ARISE-Initiative/robosuite/blob/48c1b8a6c077d04399a00db05694d7f9f876ffc9/docs/demos.md?plain=1#L37) ）

I understand that I could potentially implement the coordinate transformation myself, but for the sake of accuracy and convenience, I'm curious if there are any existing methods or tools available to achieve this.

Thank you very much in advance!

**Comment by amandlek** [comment] 2024-03-26 20:23
Seems like a duplicate of [this issue](https://github.com/ARISE-Initiative/robomimic/issues/148)

**Closed by amandlek** 2024-03-26 20:23 UTC
